[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800

lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    me-no-dev/ESPAsyncWebServer @ ^3.3.22
    adafruit/DHT sensor library @ ^1.4.4
    adafruit/Adafruit Unified Sensor @ ^1.1.9
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    z3t0/IRremote @ ^4.7.1

build_flags =
    -D CORE_DEBUG_LEVEL=1
